### ISSUE TITLE
Create separate project for field bus

### ISSUE THREAD

**Issue by craig8** [GRIDAPPSD/gridappsd-python#118]
**Is your feature request related to a problem? Please describe.**
Currently with gridappsd-python dependent on cim-graph and cim-graph dependent on a version of gridappsd-python there is a circular reference that is really difficult to get around.  cim-graph depends only on the connection for gridappd-python but not the other items, whilst it's only the field-messagebus that depends on cim-graph.  By separating these into a secondary project/wheel we can avoid this issue.

**Describe the solution you'd like**
Change gridappsd-python into a mono-repository which would have two different wheels being built out of it.  See https://gitlab.com/craig81/poetry-monorepo as an example of what I would like to do.

**Describe alternatives you've considered**
An alternative is to break this repo into multiple repositories, however I don't think that this is a good idea.

**Comment by craig8** [comment]
@afisher1 @AAndersn thoughts comments?

**Comment by craig8** [comment]
Superceeds [@GRIDAPPSD/GOSS-GRIDAPPS-D](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/issues/1714)

**Comment by poorva1209** [comment]
gridappsd-python  and gridappsd-field-bus

**Comment by craig8** [comment]
#119
